/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseIndexRouteImport } from './routes/browse.index'
import { Route as BrowseRegionSlugRouteImport } from './routes/browse.$regionSlug'
import { Route as RentalsAreaSlugRouteImport } from './routes/rentals.$areaSlug'
import { Route as BrowseRegionSlugCitySlugRouteImport } from './routes/browse.$regionSlug.$citySlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRegionSlugRoute = BrowseRegionSlugRouteImport.update({
  id: '/browse/$regionSlug',
  path: '/browse/$regionSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsAreaSlugRoute = RentalsAreaSlugRouteImport.update({
  id: '/rentals/$areaSlug',
  path: '/rentals/$areaSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRegionSlugCitySlugRoute =
  BrowseRegionSlugCitySlugRouteImport.update({
    id: '/$citySlug',
    path: '/$citySlug',
    getParentRoute: () => BrowseRegionSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse/$regionSlug': typeof BrowseRegionSlugRouteWithChildren
  '/rentals/$areaSlug': typeof RentalsAreaSlugRoute
  '/browse/': typeof BrowseIndexRoute
  '/browse/$regionSlug/$citySlug': typeof BrowseRegionSlugCitySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse/$regionSlug': typeof BrowseRegionSlugRouteWithChildren
  '/rentals/$areaSlug': typeof RentalsAreaSlugRoute
  '/browse': typeof BrowseIndexRoute
  '/browse/$regionSlug/$citySlug': typeof BrowseRegionSlugCitySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse/$regionSlug': typeof BrowseRegionSlugRouteWithChildren
  '/rentals/$areaSlug': typeof RentalsAreaSlugRoute
  '/browse/': typeof BrowseIndexRoute
  '/browse/$regionSlug/$citySlug': typeof BrowseRegionSlugCitySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse/$regionSlug'
    | '/rentals/$areaSlug'
    | '/browse/'
    | '/browse/$regionSlug/$citySlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse/$regionSlug'
    | '/rentals/$areaSlug'
    | '/browse'
    | '/browse/$regionSlug/$citySlug'
  id:
    | '__root__'
    | '/'
    | '/browse/$regionSlug'
    | '/rentals/$areaSlug'
    | '/browse/'
    | '/browse/$regionSlug/$citySlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRegionSlugRoute: typeof BrowseRegionSlugRouteWithChildren
  RentalsAreaSlugRoute: typeof RentalsAreaSlugRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$regionSlug': {
      id: '/browse/$regionSlug'
      path: '/browse/$regionSlug'
      fullPath: '/browse/$regionSlug'
      preLoaderRoute: typeof BrowseRegionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/$areaSlug': {
      id: '/rentals/$areaSlug'
      path: '/rentals/$areaSlug'
      fullPath: '/rentals/$areaSlug'
      preLoaderRoute: typeof RentalsAreaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$regionSlug/$citySlug': {
      id: '/browse/$regionSlug/$citySlug'
      path: '/$citySlug'
      fullPath: '/browse/$regionSlug/$citySlug'
      preLoaderRoute: typeof BrowseRegionSlugCitySlugRouteImport
      parentRoute: typeof BrowseRegionSlugRoute
    }
  }
}

interface BrowseRegionSlugRouteChildren {
  BrowseRegionSlugCitySlugRoute: typeof BrowseRegionSlugCitySlugRoute
}

const BrowseRegionSlugRouteChildren: BrowseRegionSlugRouteChildren = {
  BrowseRegionSlugCitySlugRoute: BrowseRegionSlugCitySlugRoute,
}

const BrowseRegionSlugRouteWithChildren =
  BrowseRegionSlugRoute._addFileChildren(BrowseRegionSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRegionSlugRoute: BrowseRegionSlugRouteWithChildren,
  RentalsAreaSlugRoute: RentalsAreaSlugRoute,
  BrowseIndexRoute: BrowseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
